### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by cldme** [zeh/key-action-binder#11]
Hi, I have a small problem. I tried to test out the KeyActionBinder to see if my joystick is actually recognized. After I placed all the classes in the right spot (with the right path) I get these errors in the console:

keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 599	1119: Access of possibly undefined property id through a reference with static type flash.ui:GameInputControl.
keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 601	1119: Access of possibly undefined property minValue through a reference with static type flash.ui:GameInputControl.
keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 609	1119: Access of possibly undefined property minValue through a reference with static type flash.ui:GameInputControl.
keyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 609	1119: Access of possibly undefined property maxValue through a reference with static type flash.ui:GameInputControlkeyActionBinding\com\zehfernando\input\binding\KeyActionBinder.as, Line 640	1119: Access of possibly undefined property DEVICE_UNUSABLE through a reference with static type Class.

Can you please help me, because I can not find what I'm doing wrong. Thanks !

**Comment by zeh** [comment]
It seems like it's trying to use the GameInputControl classes - the built-in controller classes - and they're not being found. It's likely you're exporting to a real old SWF version.

Be sure you're exporting to an Air/Flash version that supports the gamepad controls (swf target version should be around 12 or so, -target-player should be about 23 or higher). Ditto for Flash Player, has to be 12.0 or higher.

**Comment by zeh** [comment]
Closing this as I believe the above comment solves the problem. Let me know if you're still running into issues.
